require("plugin-configs.lazy")
require("plugin-configs.lsp")
require("plugin-configs.git-signs")
require("plugin-configs.catppuccin")
require("plugin-configs.tree-sitter-context")
require("plugin-configs.nerdtree")
require("plugin-configs.rgflow")
require("plugin-configs.lualine")
