vim.keymap.set("n", " ", function() end)
vim.keymap.set("n", "<c-p>", ":GFiles<CR>")
vim.keymap.set("n", "<leader>a<c-p>", ":Files<CR>")
vim.keymap.set("n", "<c-f>", ":Ag<CR>")
vim.keymap.set("n", "<leader>nt", ":NERDTreeToggle<CR>:NERDTreeRefreshRoot<CR>")
vim.keymap.set("n", "<c-u>", "<c-u>zz")
vim.keymap.set("n", "<c-d>", "<c-d>zz")
