set -g mouse on
set -g default-terminal "tmux-256color"

set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"

run /home/felipe/Documents/catppuccin-tmux/catppuccin.tmux

set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right ""

bind-key s command-prompt -I "swap-window -t "
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
